AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Username:
    Type: String
  Password:
    Type: String
    NoEcho: true
  ClusterName:
    Type: String
    Default: MyCluster
Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "MySecret-${AWS::StackName}"
      SecretString: '{"username": "${Username}", "password": "${Password}"}'
  Cluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      Engine: aurora
      EngineMode: serverless
      MasterUsername: !Sub "${MySecret.secretValue.username}"
      MasterUserPassword: !Sub "${MySecret.secretValue.password}"
      DBClusterIdentifier: !Ref ClusterName
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 1
  EncryptedSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "EncryptedSecret-${AWS::StackName}"
      SecretString: '{"username": "${MySecret.secretValue.username}", "password": "${MySecret.secretValue.password}", "host": "${Cluster.Endpoint}", "port": "${Cluster.Port}"}'
